export const imageSrc = [
  { src: 'expl-1' },
  { src: 'expl-2' },
  { src: 'expl-3' },
  { src: 'expl-4' },
  { src: 'expl-5' },
];

export const svgSrc = [
  { src: 'js', description: 'JavaScript' },
  { src: 'angular', description: 'angular' },
  { src: 'ts', description: 'TypeScript' },
  { src: 'react', description: 'React' },
  { src: 'html', description: 'HTML' },
  { src: 'css', description: 'CSS' },
  { src: 'sass', description: 'SASS' },
  { src: 'layers', description: 'Animate CSS' },
  { src: 'adaptive', description: 'Adaptive Design' },
  { src: 'resize', description: 'Responsive Design' },
  { src: 'bootstrap', description: 'Bootstrap' },
  { src: 'npm', description: 'NPM' },
  { src: 'web3', description: 'Web3 Technologies' },
  { src: 'git', description: 'Git' },
  { src: 'browsers', description: 'Browser Compatibility' },
  { src: 'document', description: 'Well Documented' },
  { src: 'charts', description: 'Charts' },
  { src: 'clean-code', description: 'Clean Code' },
  { src: 'learning', description: 'Fast learner' },
  { src: 'performance', description: 'Speed Performance' },
  { src: 'brain', description: 'Developer Friendly' },
  { src: 'support', description: 'Quick Support' },
  { src: 'soft', description: 'Strong Soft Skills' },
  { src: 'clocks', description: 'Adaptive Accessibility' },
];
